name: 'Setup ko'
description: 'Install and authorize ko'
branding:
  icon: box
  color: green
inputs:
  version:
    description: 'Version of ko to install (tip, latest-release, v0.14.1, etc.)'
    required: false
    default: 'latest-release'
  ko-version-file:
    description: 'Path to a file containing the Go version to install (if different from default)'
    required: false
    default: ''
  use-sudo:
    description: 'set to true if install-dir location requires sudo privs'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
  - shell: bash
    env:
      KO_VERSION_FILE: ${{ inputs.ko-version-file }}
      KO_VERSION: ${{ inputs.version }}
      USE_SUDO: ${{ inputs.use-sudo }}
    run: |
      set -ex

      SUDO=
      if [[ "${USE_SUDO}" == "true" ]] && command -v sudo >/dev/null; then
        SUDO=sudo
      fi

      # If KO_VERSION_FILE is set and KO_VERSION is default, read version from file
      KO_VERSION_TO_INSTALL=${KO_VERSION}
      if [[ -n "${KO_VERSION_FILE}" && "${KO_VERSION}" == "latest-release" ]]; then
        if [[ ! -f "${KO_VERSION_FILE}" ]]; then
          echo "KO_VERSION_FILE ${KO_VERSION_FILE} does not exist"
          exit 1
        fi
        KO_VERSION_TO_INSTALL=$(cat "${KO_VERSION_FILE}" | tr -d '[:space:]')
      fi

      # Install ko:
      # - if version is "tip", install from tip of main.
      # - if version is "latest-release", look up latest release.
      # - otherwise, install the specified version.
      case ${KO_VERSION_TO_INSTALL} in
      tip)
        echo "Installing ko using go install"
        go install github.com/google/ko@main
        ;;
      latest-release)
        tag=$(curl -L -s -u "username:${{ github.token }}" https://api.github.com/repos/ko-build/ko/releases/latest | jq -r '.tag_name')
        ;;
      *)
        tag="${KO_VERSION_TO_INSTALL}"
      esac

      os=${{ runner.os }}
      arch=$(echo "${{ runner.arch }}" | tr '[:upper:]' '[:lower:]')
      if [[ $os == "macOS" ]]; then
        os="Darwin"
      fi
      if [[ $arch == "x64" ]]; then
        arch="x86_64"
      fi
      if [[ ! -z ${tag} ]]; then
        echo "Installing ko @ ${tag} for ${os} ${arch}"
        curl -fsL https://github.com/ko-build/ko/releases/download/${tag}/ko_${tag:1}_${os}_${arch}.tar.gz | $SUDO tar xzf - -C /usr/local/bin ko
      fi

      if [[ ! -z ${KO_DOCKER_REPO} ]]; then
        echo "KO_DOCKER_REPO is already set"
        echo "Skipping login to ghcr.io and passing KO_DOCKER_REPO=${KO_DOCKER_REPO} on to future steps"
        echo "KO_DOCKER_REPO=${KO_DOCKER_REPO}" >> $GITHUB_ENV
      else
        # NB: username doesn't seem to matter.
        echo "${{ github.token }}" | ko login ghcr.io --username "dummy" --password-stdin

        # Set KO_DOCKER_REPO for future steps.
        # We need to get the repository name in lowercase, otherwise it could fail
        repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "KO_DOCKER_REPO=ghcr.io/${repo}"
        echo "KO_DOCKER_REPO=ghcr.io/${repo}" >> $GITHUB_ENV
      fi
