name: 'Setup ko'
description: 'Install and authorize ko'
branding:
  icon: box
  color: green
inputs:
  version:
    description: 'Version of ko to install (tip, latest-release, v0.18.1, etc.)'
    required: true
    default: 'latest-release'
  token:
    description: 'The token used to authenticate requests to GitHub.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node24'
  main: 'dist/setup/index.js'
